### ISSUE TITLE
mex.h is missing

### ISSUE THREAD

**Issue by CharlesJQuarra** [moonsdad/vinci#1]
Apparently there are missing headers or dependencies, when trying to build this, I got this error:

``` 
gcc vinci_volume.c -c -O3 -Wall -ansi -pedantic
vinci_volume.c:23:10: fatal error: mex.h: No such file or directory
 #include "mex.h"
          ^~~~~~~
compilation terminated.
```

**Comment by hildigerr** [comment]
The mex.h file is generated with Matlab. I no longer have a license to use Matlab, so I'm not sure how to generate it now, but nine years ago it was with the command:

`mex v_vol.c vinci_global.c vinci_memory.c vinci_set.c vinci_lass.c vinci_file.c`

This was noted as a comment in the makefile in commit 7f44585, though admittedly a README would probably be more helpful.

If you don't want to use Matlab: The original Vinci from which this was forked can be retrieved from [archive.org](https://web.archive.org/web/20070416033412/http://www.lix.polytechnique.fr:80/Labo/Andreas.Enge/Vinci.html) (or just checkout commit 7e3b549).

As an aside: This was updated to use Matlab Builder for the website [geometrictomography.com](http://www.geometrictomography.com) which interactively showcases the algorithms.
